### ISSUE TITLE
/entrypoint.sh: line 62:    64 Illegal instruction

### ISSUE THREAD

**Issue by extremeshok** [syakesaba/docker-sslbump-proxy#1]
docker logs sslbump-proxy
'''
/entrypoint.sh: line 62:    64 Illegal instruction     $SQUID_DIR/sbin/squid -d 10 -f $SQUID_DIR/etc/squid.conf
'''

**Comment by syakesaba** [comment]
I've tested docker build and run, but no such error occurred.
Could you tell me your environment?
my env: Linux 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux (CentOS 7 EL7)
