### ISSUE TITLE
libssl1.0-dev has no installation candidate

### ISSUE THREAD

**Issue by caozhzh** [syakesaba/docker-sslbump-proxy#2]
debian had no libssl1.0-dev
changed FROM debian:latest to FROM ubuntu:latest, and ok

**Comment by syakesaba** [comment]
Thank you report that.
Maybe It's same issue described in the link below.
https://github.com/squid-cache/squid/pull/333
and sadly the error occur when I replaced the base OS to "ubuntu:latest".

I'll try debian:jessie.

**Comment by syakesaba** [comment]
https://github.com/syakesaba/docker-sslbump-proxy/commit/a85d1e37540893341f834a675161f6e71058cf35

**Comment by caozhzh** [comment]
aha, debian:jessie is ok
