### ISSUE TITLE
error installing squid

### ISSUE THREAD

**Issue by phillippc** [syakesaba/docker-sslbump-proxy#3]
ls: cannot access '.': Operation not permitted
configure: error: working directory cannot be determined
The command '/bin/sh -c wget http://www.squid-cache.org/Versions/v4/squid-4.13.tar.gz &&     tar xzvf squid-4.13.tar.gz &&     cd squid-4.13 &&     ./configure --prefix=$SQUID_DIR --with-openssl --enable-ssl-crtd --with-large-files &&     make -j4 &&     make install' returned a non-zero code: 2

**Comment by syakesaba** [comment]
Thank you man, Fixed URI.
